#!/usr/bin/env python3
"""
Build the customer dimension from the transactional data (canonical name per
customer_code = most frequent raw spelling) and left-join the AR snapshot
(2026-07-04) transcribed from the 8 "مديونية" PDFs where the code matches.

Note: the AR snapshot is a POINT-IN-TIME balance report generated by the
company's own ERP for its 8 sales reps/territories, covering only customers
who carry a non-zero balance on 2026-07-04. It is NOT a full customer master
list, so customers with n_rows_ar = 0 below simply had no outstanding balance
on that date (or their account is otherwise not in that rep's book) -- this
is not a data quality defect.
"""
import json
import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TX_CSV = ROOT / "data" / "processed" / "sales_transactions_enriched.csv"
AR_CSV = ROOT / "data" / "processed" / "ar_customer_balances_2026-07-04.csv"
OUT_DIM_CUST = ROOT / "data" / "processed" / "dim_customers.csv"
OUT_LOG = ROOT / "data" / "processed" / "customer_dim_log.json"


def main():
    df = pd.read_csv(TX_CSV, dtype={"customer_code": str})
    ar = pd.read_csv(AR_CSV, dtype={"customer_code": str})
    ar["net_balance"] = ar["debit"] - ar["credit"]

    g = df.groupby("customer_code").agg(
        customer_name=("customer_name_raw", lambda s: s.value_counts().index[0]),
        n_invoices=("invoice_no", "nunique"),
        total_revenue=("line_total", "sum"),
        first_invoice_date=("invoice_date", "min"),
        last_invoice_date=("invoice_date", "max"),
        n_name_variants=("customer_name_raw", "nunique"),
    ).reset_index()

    ar_dedup = ar.groupby("customer_code").agg(
        rep=("rep", "first"),
        city=("city", "first"),
        ar_net_balance=("net_balance", "sum"),
    ).reset_index()

    dim = g.merge(ar_dedup, on="customer_code", how="left")
    dim["has_ar_snapshot"] = dim["rep"].notna()
    dim = dim.sort_values("total_revenue", ascending=False)
    dim.to_csv(OUT_DIM_CUST, index=False, encoding="utf-8")

    log = dict(
        n_customers_in_transactions=len(g),
        n_customers_in_ar_snapshot=ar["customer_code"].nunique(),
        n_customers_matched=int(dim["has_ar_snapshot"].sum()),
        n_customers_with_multiple_name_variants=int((g["n_name_variants"] > 1).sum()),
        ar_customers_not_in_transactions=sorted(set(ar["customer_code"]) - set(g["customer_code"])),
    )
    with open(OUT_LOG, "w", encoding="utf-8") as f:
        json.dump(log, f, ensure_ascii=False, indent=2)
    print(json.dumps(log, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
